app:
  name: "snap-aspi-go"
  version: "1.0.0"
  environment: "${APP_ENV:development}"

server:
  host: "${SERVER_HOST:localhost}"
  port: "${SERVER_PORT:8080}"
  read_timeout: "${SERVER_READ_TIMEOUT:30s}"
  write_timeout: "${SERVER_WRITE_TIMEOUT:30s}"

logging:
  level: "${LOG_LEVEL:info}"
  format: "${LOG_FORMAT:json}"
  output: "${LOG_OUTPUT:stdout}"

aspi:
  base_url: "${ASPI_BASE_URL:https://sandbox.bi-sandbox.id}"
  client_id: "${ASPI_CLIENT_ID}"
  client_secret: "${ASPI_CLIENT_SECRET}"
  private_key_path: "${ASPI_PRIVATE_KEY_PATH:}"
  public_key_path: "${ASPI_PUBLIC_KEY_PATH:}"

  endpoints:
    b2b_token: "api/v1.0/access-token/b2b"
    b2b2c_token: "api/v1.0/access-token/b2b2c"

  timeouts:
    connect_timeout: "${ASPI_CONNECT_TIMEOUT:10s}"
    request_timeout: "${ASPI_REQUEST_TIMEOUT:30s}"

  retry:
    max_attempts: 3
    backoff_duration: "${ASPI_BACKOFF_DURATION:1s}"
