app:
  name: "snap-aspi-go"
  version: "1.0.0"
  environment: "development"

server:
  host: "localhost"
  port: "8080"
  read_timeout: 30s
  write_timeout: 30s

logging:
  level: "info"
  format: "json"
  output: "stdout"

aspi:
  base_url: "${ASPI_BASE_URL:https://sandbox.aspi-indonesia.or.id}"
  client_id: "${ASPI_CLIENT_ID:your-client-id}"
  client_secret: "${ASPI_CLIENT_SECRET:your-client-secret}"
  private_key_path: "${ASPI_PRIVATE_KEY_PATH:keys/private_key.pem}"
  public_key_path: "${ASPI_PUBLIC_KEY_PATH:keys/public_key.pem}"

  endpoints:
    b2b_token: "/api/v1.0/access-token/b2b"
    b2b2c_token: "/api/v1.0/access-token/b2b2c"

  timeouts:
    connect_timeout: 10s
    request_timeout: 30s

  retry:
    max_attempts: 3
    backoff_duration: 1s
